- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - node_prep

- name: Install K3s server
  hosts: k3s_servers
  become: true
  roles:
    - k3s_server

- name: Install K3s agents
  hosts: k3s_agents
  become: true
  roles:
    - k3s_agent
    